changeLogFile=changelog/db.changelog-master.yaml
url=jdbc:mysql://localhost:3306/quickbooks?useSSL=false&allowPublicKeyRetrieval=true
username=qb_admin
password=qb_admin_pass
classpath=../mysql-connector-j-8.3.0.jar
parameter.CDC_READER_PASSWORD=cdc_reader_pass