"""Generate the 10 QB user accounts (companies table)."""

# These are hardcoded — they're the anchors of the graph.
# Each represents a real QB user in the Austin construction ecosystem.

QB_ACCOUNTS = [
    {
        "company_id": 1,
        "company_name": "Acme Construction Co",
        "legal_name": "Acme Construction Co LLC",
        "legal_structure": "LLC",
        "ein": "74-3218976",
        "industry_category": "Commercial Building",
        "street_address": "4200 S Congress Ave, Ste 300",
        "city": "Austin",
        "state": "TX",
        "zip": "78745",
        "primary_contact": "Marcus Rivera",
        "email": "marcus@acmeconstruction.com",
        "phone": "512-555-0101",
        "website": "www.acmeconstruction.com",
    },
    {
        "company_id": 2,
        "company_name": "BuildRight General Contractors",
        "legal_name": "BuildRight GC Inc",
        "legal_structure": "Corporation",
        "ein": "74-5529841",
        "industry_category": "General Contracting",
        "street_address": "1800 E 6th St",
        "city": "Austin",
        "state": "TX",
        "zip": "78702",
        "primary_contact": "Jennifer Walsh",
        "email": "jen@buildright.com",
        "phone": "512-555-0102",
        "website": "www.buildright.com",
    },
    {
        "company_id": 3,
        "company_name": "Hill Country Homes",
        "legal_name": "Hill Country Homes LLC",
        "legal_structure": "LLC",
        "ein": "74-6618234",
        "industry_category": "Home Building",
        "street_address": "500 Mercer St",
        "city": "Dripping Springs",
        "state": "TX",
        "zip": "78620",
        "primary_contact": "Robert Chen",
        "email": "rob@hillcountryhomes.com",
        "phone": "512-555-0103",
        "website": "www.hillcountryhomes.com",
    },
    {
        "company_id": 4,
        "company_name": "Lone Star Renovations",
        "legal_name": "Lone Star Renovations",
        "legal_structure": "Sole Proprietorship",
        "ein": "74-1127653",
        "industry_category": "Remodeling",
        "street_address": "2100 N Mays St",
        "city": "Round Rock",
        "state": "TX",
        "zip": "78664",
        "primary_contact": "David Kowalski",
        "email": "david@lonestarreno.com",
        "phone": "512-555-0104",
        "website": "www.lonestarreno.com",
    },
    {
        "company_id": 5,
        "company_name": "Capital City Plumbing",
        "legal_name": "Capital City Plumbing LLC",
        "legal_structure": "LLC",
        "ein": "74-8842109",
        "industry_category": "Plumbing Services",
        "street_address": "900 Industrial Blvd",
        "city": "Austin",
        "state": "TX",
        "zip": "78721",
        "primary_contact": "Amanda Torres",
        "email": "amanda@capcityplumbing.com",
        "phone": "512-555-0105",
        "website": "www.capcityplumbing.com",
    },
    {
        "company_id": 6,
        "company_name": "ATX Electrical Solutions",
        "legal_name": "ATX Electrical Solutions LLC",
        "legal_structure": "LLC",
        "ein": "74-3356721",
        "industry_category": "Electrical Work",
        "street_address": "3500 Burnet Rd, Unit 12",
        "city": "Austin",
        "state": "TX",
        "zip": "78756",
        "primary_contact": "Chris Nakamura",
        "email": "chris@atxelectrical.com",
        "phone": "512-555-0106",
        "website": "www.atxelectrical.com",
    },
    {
        "company_id": 7,
        "company_name": "Precision HVAC Systems",
        "legal_name": "Precision HVAC Systems Corp",
        "legal_structure": "Corporation",
        "ein": "74-9917345",
        "industry_category": "HVAC",
        "street_address": "1200 Whitestone Blvd",
        "city": "Cedar Park",
        "state": "TX",
        "zip": "78613",
        "primary_contact": "Michael Santos",
        "email": "mike@precisionhvac.com",
        "phone": "512-555-0107",
        "website": "www.precisionhvac.com",
    },
    {
        "company_id": 8,
        "company_name": "RedLine Interiors",
        "legal_name": "RedLine Interiors LLC",
        "legal_structure": "LLC",
        "ein": "74-2204568",
        "industry_category": "Interior Design",
        "street_address": "2200 S Lamar Blvd",
        "city": "Austin",
        "state": "TX",
        "zip": "78704",
        "primary_contact": "Sophia Patel",
        "email": "sophia@redlineinteriors.com",
        "phone": "512-555-0108",
        "website": "www.redlineinteriors.com",
    },
    {
        "company_id": 9,
        "company_name": "Travis County Property Mgmt",
        "legal_name": "Travis County Property Management Corp",
        "legal_structure": "Corporation",
        "ein": "74-7783201",
        "industry_category": "Property Management",
        "street_address": "800 Barton Springs Rd, Ste 400",
        "city": "Austin",
        "state": "TX",
        "zip": "78704",
        "primary_contact": "Elena Varga",
        "email": "elena@tcproperty.com",
        "phone": "512-555-0109",
        "website": "www.tcproperty.com",
    },
    {
        "company_id": 10,
        "company_name": "Bluebonnet Landscaping",
        "legal_name": "Bluebonnet Landscaping",
        "legal_structure": "Sole Proprietorship",
        "ein": None,
        "industry_category": "Lawn and Garden",
        "street_address": "15800 FM 620",
        "city": "Pflugerville",
        "state": "TX",
        "zip": "78660",
        "primary_contact": "Jorge Mendoza",
        "email": "jorge@bluebonnetlandscape.com",
        "phone": "512-555-0110",
        "website": None,
    },
]
