"""Shared reference data used across generators."""

# ── Name pools ──

FIRST_NAMES = [
    "Bob", "Jim", "Mike", "Dave", "Steve", "Tom", "Joe", "Bill", "Rick",
    "Dan", "Mark", "Chris", "Jeff", "Brian", "Gary", "Larry", "Ray",
    "Scott", "Kevin", "Paul", "Jason", "Matt", "Tony", "Frank", "Carlos",
    "Maria", "Lisa", "Sarah", "Amy", "Karen", "Linda", "Susan", "Nancy",
    "Rosa", "Elena", "Juan", "Pedro", "Luis", "Marco", "Anna", "Beth",
    "Greg", "Doug", "Wayne", "Keith", "Terry", "Randy", "Dennis", "Jerry",
]

LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Martinez",
    "Davis", "Rodriguez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore",
    "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris",
    "Clark", "Lewis", "Robinson", "Walker", "Hall", "Allen", "Young",
    "King", "Wright", "Hill", "Scott", "Green", "Adams", "Baker",
    "Nelson", "Carter", "Mitchell", "Roberts", "Turner", "Phillips",
    "Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Reed",
]

LOCATION_DESCRIPTORS = [
    "Austin", "Central Texas", "ATX", "Lone Star", "Capital City",
    "Hill Country", "Travis County", "Round Rock", "Cedar Park",
    "Greater Austin", "South Austin", "North Austin", "East Austin",
    "Lakeway", "Texas", "TX",
]

BUSINESS_SUFFIXES = [
    "LLC", "Inc", "Co", "Corp", "Services", "Solutions", "Supply",
    "Enterprises", "Group", "& Sons", "& Co", "Pro", "Plus", "Express",
    "Specialists", "Experts", "Team", "Works", "Masters", "Direct",
]

PAYMENT_TERMS = ["due_on_receipt", "net_15", "net_30", "net_60"]


# ── Austin metro street data ──

STREET_NAMES = [
    "Congress Ave", "Lamar Blvd", "Burnet Rd", "S 1st St", "E Riverside Dr",
    "N Mopac Expy", "Research Blvd", "S Lamar Blvd", "Guadalupe St",
    "Red River St", "Manor Rd", "Airport Blvd", "Manchaca Rd", "Oltorf St",
    "William Cannon Dr", "Slaughter Ln", "Parmer Ln", "Braker Ln",
    "Anderson Mill Rd", "Great Hills Trl", "Spicewood Springs Rd",
    "Bee Caves Rd", "Westlake Dr", "Lake Austin Blvd", "Exposition Blvd",
    "S Congress Ave", "E 7th St", "E 6th St", "Cesar Chavez St",
    "Barton Springs Rd", "S Mays St", "E Palm Valley Blvd",
    "University Ave", "N IH-35", "S IH-35", "US-183", "FM 620",
    "FM 1431", "Ranch Rd 2222", "Ranch Rd 620", "Whitestone Blvd",
    "Main St", "Center St", "Oak Hill Dr", "Industrial Blvd",
    "Commerce Dr", "Tradesman Dr", "Contractor Way", "Builder Ln",
    "Market St", "Frontage Rd",
]

SUITE_TYPES = ["Ste", "Suite", "Unit", "#", "Bldg"]

ZIP_CODES = {
    "Austin": ["78701", "78702", "78703", "78704", "78721", "78723",
               "78741", "78745", "78748", "78749", "78750", "78751",
               "78752", "78753", "78756", "78757", "78758", "78759"],
    "Round Rock": ["78664", "78665", "78681"],
    "Cedar Park": ["78613"],
    "Pflugerville": ["78660"],
    "Georgetown": ["78626", "78628"],
    "Dripping Springs": ["78620"],
    "Kyle": ["78640"],
    "San Marcos": ["78666"],
    "Lakeway": ["78734"],
    "Bee Cave": ["78738"],
    "Leander": ["78641"],
    "Liberty Hill": ["78642"],
    "San Antonio": ["78201", "78205", "78207", "78215", "78230"],
    "Houston": ["77001", "77002", "77003", "77008", "77019"],
    "Dallas": ["75201", "75202", "75204"],
}


# ── Category → trade word mapping ──

TRADE_WORDS = {
    "Lumber": ["Lumber", "Timber", "Wood"],
    "Concrete": ["Concrete", "Masonry"],
    "Hardware": ["Hardware", "Fastener", "Tool"],
    "Plumbing": ["Plumbing", "Pipe", "Plumb"],
    "Electrical": ["Electric", "Electrical", "Power"],
    "HVAC": ["HVAC", "Climate", "Air", "Heating & Cooling"],
    "Paint": ["Paint", "Coatings", "Color"],
    "Roofing": ["Roofing", "Roof"],
    "Flooring": ["Flooring", "Floor", "Tile"],
    "Equipment Rental": ["Equipment", "Rental", "Machinery"],
    "Tool": ["Tool", "Equipment"],
    "Drywall": ["Drywall", "Interior"],
    "Painting": ["Painting", "Paint"],
    "Landscaping": ["Landscaping", "Lawn", "Garden", "Landscape"],
    "Paving": ["Concrete", "Paving"],
    "Architectural": ["Architecture", "Design", "Architects"],
    "Engineering": ["Engineering", "Engineers"],
    "Surveying": ["Survey", "Surveying", "Land"],
    "Waste": ["Waste", "Disposal", "Hauling"],
    "Insurance": ["Insurance", "Risk"],
    "Accounting": ["Accounting", "Tax", "Bookkeeping"],
    "Trucking": ["Trucking", "Hauling", "Delivery", "Transport"],
    "Homeowner": None,
    "Commercial": ["Development", "Properties", "Realty"],
    "Restaurant": ["Hospitality", "Restaurant", "Dining"],
    "Retail": ["Retail", "Stores", "Shop"],
    "Office": ["Tech", "Solutions", "Digital"],
    "Healthcare": ["Medical", "Health", "Care"],
    "Church": ["Community", "Faith", "Ministry"],
    "School": ["Education", "School", "Academy"],
    "Municipal": ["Municipal", "Public", "City"],
    "Property Management": ["Property", "Management", "Realty"],
    "HOA": ["Community", "Estates", "Ridge", "Creek"],
    "General Contractor": ["Construction", "Builders", "Building"],
    "Interior Design": ["Interiors", "Design", "Décor"],
    "Real Estate": ["Realty", "Properties", "Investments", "Homes"],
}


# ── Vendor category definitions ──
# (label, naics, count_in_pool, commodity_examples, city_pool)

VENDOR_CATEGORIES = [
    ("Lumber & Building Materials", "423310", 10,
     ["lumber", "plywood", "framing materials", "OSB sheathing"],
     ["Austin", "San Antonio", "Houston"]),
    ("Concrete & Masonry Supply", "423320", 5,
     ["ready-mix concrete", "rebar", "concrete blocks", "mortar"],
     ["Austin", "Round Rock", "San Marcos"]),
    ("Hardware & Fasteners", "423710", 5,
     ["screws", "nails", "bolts", "anchors", "hand tools"],
     ["Austin", "Cedar Park", "Georgetown"]),
    ("Plumbing Supply", "423720", 8,
     ["PVC pipe", "copper fittings", "water heaters", "fixtures"],
     ["Austin", "Pflugerville", "Round Rock"]),
    ("Electrical Supply", "423610", 7,
     ["wire", "conduit", "breaker panels", "lighting fixtures"],
     ["Austin", "Cedar Park", "San Marcos"]),
    ("HVAC Supply & Equipment", "423730", 5,
     ["ductwork", "AC units", "furnaces", "thermostats"],
     ["Austin", "Round Rock", "San Antonio"]),
    ("Paint & Coatings", "424950", 4,
     ["interior paint", "exterior paint", "stain", "primer"],
     ["Austin", "Dripping Springs"]),
    ("Roofing Materials", "423330", 4,
     ["shingles", "underlayment", "flashing", "gutters"],
     ["Austin", "Kyle", "San Marcos"]),
    ("Flooring Supply", "423220", 4,
     ["hardwood flooring", "tile", "carpet", "vinyl plank"],
     ["Austin", "Round Rock", "Cedar Park"]),
    ("Equipment Rental", "532412", 6,
     ["excavator rental", "skid steer", "scaffolding", "generators"],
     ["Austin", "Round Rock", "San Marcos"]),
    ("Tool & Equipment Sales", "423810", 3,
     ["power tools", "saws", "drills", "compressors"],
     ["Austin", "San Antonio"]),
    ("Plumbing Contractor", "238220", 6,
     ["plumbing installation", "pipe repair", "water heater install"],
     ["Austin", "Round Rock", "Pflugerville", "Cedar Park"]),
    ("Electrical Contractor", "238210", 5,
     ["electrical wiring", "panel upgrades", "lighting install"],
     ["Austin", "Cedar Park", "Georgetown"]),
    ("HVAC Contractor", "238220", 4,
     ["AC installation", "duct cleaning", "furnace repair"],
     ["Austin", "Round Rock", "Cedar Park"]),
    ("Drywall & Insulation", "238310", 3,
     ["drywall hanging", "insulation install", "mudding and taping"],
     ["Austin", "Kyle"]),
    ("Painting Contractor", "238320", 3,
     ["interior painting", "exterior painting", "commercial painting"],
     ["Austin", "Dripping Springs", "Round Rock"]),
    ("Landscaping Services", "561730", 4,
     ["lawn maintenance", "irrigation", "tree trimming", "sod install"],
     ["Austin", "Pflugerville", "Cedar Park"]),
    ("Concrete & Paving", "238110", 3,
     ["foundation pour", "driveway paving", "flatwork"],
     ["Austin", "Round Rock"]),
    ("Architectural Services", "541310", 2,
     ["blueprints", "design plans", "permit drawings"],
     ["Austin"]),
    ("Engineering Services", "541330", 2,
     ["structural engineering", "civil engineering", "MEP design"],
     ["Austin", "San Antonio"]),
    ("Surveying", "541370", 2,
     ["land survey", "boundary survey", "topographic survey"],
     ["Austin", "Georgetown"]),
    ("Waste & Dumpster Services", "562111", 3,
     ["dumpster rental", "debris removal", "recycling"],
     ["Austin", "Round Rock", "Pflugerville"]),
    ("Insurance", "524210", 2,
     ["general liability", "workers comp", "builders risk"],
     ["Austin", "Dallas"]),
    ("Accounting & Bookkeeping", "541211", 2,
     ["bookkeeping", "tax preparation", "payroll services"],
     ["Austin"]),
    ("Trucking & Delivery", "484110", 3,
     ["material delivery", "flatbed hauling", "dump truck services"],
     ["Austin", "San Marcos", "Kyle"]),
]

CLIENT_CATEGORIES = [
    ("Homeowner - Renovation", "N/A", 20,
     ["kitchen remodel", "bathroom renovation", "room addition"],
     ["Austin", "Dripping Springs", "Lakeway", "Round Rock", "Cedar Park",
      "Pflugerville", "Georgetown", "Bee Cave"]),
    ("Homeowner - New Build", "N/A", 10,
     ["custom home build", "spec home", "garage conversion"],
     ["Dripping Springs", "Lakeway", "Georgetown", "Liberty Hill", "Leander"]),
    ("Commercial Property Developer", "531311", 8,
     ["office buildout", "retail space", "mixed-use development"],
     ["Austin", "Round Rock", "San Marcos"]),
    ("Restaurant & Hospitality", "722511", 6,
     ["restaurant buildout", "bar renovation", "hotel remodel"],
     ["Austin", "Round Rock"]),
    ("Retail Business", "441000", 5,
     ["storefront buildout", "tenant improvement", "display install"],
     ["Austin", "Cedar Park", "Round Rock"]),
    ("Office & Tech Company", "541511", 5,
     ["office renovation", "server room build", "open floor conversion"],
     ["Austin"]),
    ("Healthcare Facility", "621111", 4,
     ["clinic buildout", "dental office", "medical suite renovation"],
     ["Austin", "Round Rock", "Cedar Park"]),
    ("Church & Nonprofit", "813110", 3,
     ["sanctuary renovation", "community center", "facility upgrade"],
     ["Austin", "Pflugerville", "Georgetown"]),
    ("School District", "611110", 3,
     ["classroom addition", "gym renovation", "portable building"],
     ["Austin", "Round Rock", "Pflugerville"]),
    ("Municipal / Government", "921110", 3,
     ["public works", "park facility", "government office remodel"],
     ["Austin", "Round Rock"]),
    ("Property Management Company", "531311", 8,
     ["maintenance contract", "unit turnover", "common area upgrade"],
     ["Austin", "Round Rock", "Cedar Park", "Pflugerville"]),
    ("HOA / Community Association", "813990", 5,
     ["pool house repair", "clubhouse renovation", "fence replacement"],
     ["Austin", "Lakeway", "Cedar Park", "Georgetown"]),
    ("General Contractor (Sub-to)", "236220", 10,
     ["subcontract work", "specialty trade", "project-based"],
     ["Austin", "Round Rock", "San Marcos", "San Antonio"]),
    ("Interior Design Firm", "541410", 4,
     ["design-build project", "furnishing install", "custom millwork"],
     ["Austin", "Dripping Springs"]),
    ("Real Estate Agent/Investor", "531210", 6,
     ["flip project", "investment property", "pre-sale renovation"],
     ["Austin", "Round Rock", "Cedar Park", "Georgetown"]),
]
